### ISSUE TITLE
Bug with iframe due to wrong shouldOverrideUrlLoading implementation

### ISSUE THREAD

**Issue by jakub-g** [lsrom/webview-tester#2] opened 2020-02-25 15:49 UTC
Hi, thanks for creating the project and putting it to the PlayStore. It's been helpful for testing a bug report I got.

I reproduced the bug with webview-tester and reported an issue to Chrome, but turns out the problem is linked to the WebView implementation:

Check this response of Chromium engineer:

https://bugs.chromium.org/p/chromium/issues/detail?id=1054335#c4

The faulty code is here:

https://github.com/lsrom/webview-tester/blob/master/app/src/main/java/cz/lsrom/webviewtest/WebViewFragment.java#L96-L97

and it's exactly doing the thing that is described as "do not do" in Android docs:

https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20android.webkit.WebResourceRequest)

Because of this, when the page under test has an iframe, it can be that contents of iframe will be loaded unexpectedly in top level.

**Comment by lsrom** [comment] 2020-02-25 19:19
Thanks for your feedback! This should be fixed in new 2.1 version that should be live on Google Play soon so please check it out if the problem is solved.

**Closed as completed by lsrom** 2020-02-25 19:19 UTC
